### ISSUE TITLE
Clarify relation with JSON Home

### ISSUE THREAD

**Issue by dret** [api-commons/api-json#69]
It would be good to look at how this relates to JSON home, and what the relationship is. It seems that the overall goals have a lot of overlap. https://tools.ietf.org/html/draft-nottingham-json-home

**Comment by kinlane** [comment]
Definitely. Working on story to help flush out my thoughts. I'd like to establish a venn diagram with JSON Home, APIs.json, and you also pointed out http://pivio.io/.  Will publish link to my thoughts here shortly.

**Comment by dret** [comment]
On 2017-07-31 18:52, Kin Lane wrote:
> Definitely. Working on story to help flush out my thoughts. I'd like to 
> establish a venn diagram with JSON Home, APIs.json, and you also pointed 
> out http://pivio.io/. Will publish link to my thoughts here shortly.

after thinking about this for a while it seems to me that there is a 
difference between the two. APIs.json is more about describing the API 
in its entirety, providing metadata about it. JSON home is more about 
providing information for an API's "entry/starting" points, so it's more 
narrowly technical. but it still might make sense to provide some 
context for people wondering about the relationship.

**Comment by kinlane** [comment]
Correct. APIs.json is operations centered. My goal is to reference OpenAPI, JSON Home, and others within an index, but really push for other operational references--many are simply HTML links, but when possible I want it to be a waiting room for the development of other operational level machine readable specifications, like API Commons (licensing) and API Plans (pricing  & composition), or maybe even TOS and SLA.

**Comment by dret** [comment]
On 2017-08-01 10:39, Kin Lane wrote:
> Correct. APIs.json is operations centered.

in that case definitely have a look at pivio. the way i presented things 
at our virtual summit in mid-july, there's quite a bit of overlap, but:

* APIs.json focuses on the format only and the extension model seems to 
be a bit unclear right now.

* pivio focuses on infrastructure and the format is mostly a by-product 
and seems to be tightly coupled with the project.

ideally, there should be both: a format that's well-defined and open and 
extensible, and infrastructure people might want to reuse to leverage 
that format.

@mamund and i have been working with that idea and we're trying to build 
something. the idea is to have a validator and an aggregator as well as 
an open registry of well-known extensions. however, we only started 
recently and this might take a little while to get done. but we do think 
we have a good idea of the key ingredients.


> My goal is to reference 
> OpenAPI, JSON Home, and others within an index, but really push for 
> other operational references--many are simply HTML links, but when 
> possible I want it to be a waiting room for the development of other 
> operational level machine readable specifications, like API Commons 
> (licensing) and API Plans (pricing & composition), or maybe even TOS and 
> SLA.

for some of these there are link relations already, so if you have a 
general model of how to reuse link relations, this is pretty much 
covered. i think an important issue here is to be clear about the facets 
that should be covered by value (part of the format), covered by 
reference (part of other formats), and make sure that this is 
communicated clearly.

**Comment by kinlane** [comment]
Right now, there is no formal link relations strategy. Simply a label called "type". My intention was to get feedback from community, and introduce new model for link relations based upon existing. 

Agreed on the communication about the facets covered -- I call this the essential building blocks of API operations. Making sure they are well defined, clearly communicated to API providers is crucial.

I am diving into Pivio, and refreshing JSON Home, because I honestly don't have fully loaded in my brain. 

Look forward to learning more about what you and @mamund are working on. I'd like to think about future of APIs.json (including name change) going into fall, and revisit the roadmap.

**Comment by dret** [comment]
> Agreed on the communication about the facets covered -- I call this the 
> essential building blocks of API operations. Making sure they are well 
> defined, clearly communicated to API providers is crucial.

you will find that pivio is more on the tech side of operational facets 
than you are. definitely some overlap but also some differences. the 
most important part is to figure out why you want such a format to 
exist, what you're building into it to help in the scenarios you're 
considering, and how you're expecting the format to help on the open 
internet and/or in other open service landscapes.

**Comment by kinlane** [comment]
First thing that caught my attention is the service level focus. Which quickly transcends many web only aspects of APIs, which I think is important, but I need to grasp at deeper level, and see more examples.

**Comment by dret** [comment]
On 2017-08-01 11:02, Kin Lane wrote:
> Look forward to learning more about what you and @mamund 
> <https://github.com/mamund> are working on. I'd like to think about 
> future of APIs.json (including name change) going into fall, and revisit 
> the roadmap.

https://github.com/dret/servmeta/blob/master/format.md#iana-link-relation-values 
is our first stab and already hints at our general approach: reuse as 
much as possible, listing all the link relations that are already 
defined and that we would like to see/encourage being used.

the key to this will be to build machinery around this so that people 
understand how to use is well. @mamund is tackling building a validator 
and an aggregator, i am trying to figure out the registry side of 
things. still very early but at least we have a general idea where we 
want to with this.

**Comment by kinlane** [comment]
Nice. Definitely looks like some good overlap. I'd love to learn more about service-desc, service-doc, and service-meta. 

I'd love to talk about validation, splitter, aggregator, translator, crawler (github, web). 

I like the direction.

**Comment by kinlane** [comment]
I'll share more links as they come off the assembly line, but the list of "channel types" (needs new name) is dynamically driven.

- Aggregate of 1,178 APIs.json I have in my stack - http://theapistack.com/channel-types/

or smaller stacks:

- Microsoft: http://microsoft.stack.network/channel-types/
- Google: http://google.stack.network/channel-types/
- AWS: http://amazon.web.services.stack.network/channel-types/
- Facebook: http://facebook.stack.network/channel-types/

Of course, they are limited to whatever I profile about each API. The more I profile, the more building blocks of operations emerge. 

The more APIs I had to my stack, the more reflections of API operations I see...

**Comment by dret** [comment]
On 2017-08-01 12:26, Kin Lane wrote:
> Nice. Definitely looks like some good overlap. I'd love to learn more 
> about service-desc, service-doc, and service-meta.

i am working on a new version of the draft right now. 
https://github.com/dret/I-D/issues/63 is what @mamund and i added for 
servmeta, and my goal is to finish an updated version of 
https://tools.ietf.org/html/draft-wilde-service-link-rel today. i would 
love your feedback!

* service-desc should link to (mostly) machine-oriented descriptions 
such as OpenAPI.

* service-doc should link to (mostly) human-oriented descriptions that 
often may be HTML or PDF.

* service-meta should link to service metadata that, among other things, 
can make descriptions and documentation discoverable. APIs.json and 
pivio and servmeta are examples for this kind of information.

> I'd love to talk about validation, splitter, aggregator, translator, 
> crawler (github, web).

so do we! maybe @mamund and the two of us can set a bit of time aside in 
boulder to chat about these topics. it is my goal to make (some) 
progress on servmeta, the draft-wilde-service-link-rel draft, and the 
registry side of things until then.

**Comment by dret** [comment]
as promised:

On 2017-08-01 12:40, Erik Wilde wrote:
> i am working on a new version of the draft right now. 
> https://github.com/dret/I-D/issues/63 is what @mamund and i added for 
> servmeta, and my goal is to finish an updated version of 
> https://tools.ietf.org/html/draft-wilde-service-link-rel today. i would 
> love your feedback!

https://tools.ietf.org/html/draft-wilde-service-link-rel-04

**Comment by kinlane** [comment]
Got alerted to another format - http://www.microdocs.io/ 

Will be diving into and profiling and loading up into the ol brain.

**Comment by dret** [comment]
On 2017-08-10 09:36, Kin Lane wrote:
> Got alerted to another format - http://www.microdocs.io/
> Will be diving into and profiling and loading up into the ol brain.

good pointer, that's a new one for me as well. it'll be interesting to 
see how it compares to APIs.json, JSON home, servmeta, pivio, and the 
likes. looking forward to your point of view!
