### ISSUE TITLE
[Question] Is still active project? 

### ISSUE THREAD

**Issue by GrooveCS** [api-commons/api-json#76]
I found a few issues on [APIs JSON landing page](http://apisjson.org/index.html). When determining how to open issue to resolve the issue, now wondering if the project is still active? 

**Concerns**

1. The side doesn't default to https from http
1. The Trade.gov logo is not rendering properly
1. No blog post since 2016

![APIs json](https://user-images.githubusercontent.com/1635152/91877521-1576d380-ec4c-11ea-98ae-d5769e5312c0.jpg)

**Comment by kinlane** [comment]
Yes it is active. Needs investment is all. We've been waiting for conversations in OpenAPI to move forward, but they haven't so we'll be making more investment ASAP. Fixed that image.

**Comment by GrooveCS** [comment]
Are you open to see how we can assist?

**Comment by kinlane** [comment]
Yes, always open to people helping move forward. Ping me info@apievangelist.com and we can chat more, or feel free to drive publicly via issues!
