### ISSUE TITLE
Current Status (early 2024)

### ISSUE THREAD

**Issue by ChristophWeber** [api-commons/api-json#77]
Hi all, what is the status of apis.json? Any plans to push it further? I noticed that [WebAPI Schema RFC](https://webapi-discovery.github.io/rfcs/rfc0001.html) references apis.json (as well as some other related data formats). However WebAPI Schema has stalled too.

For context, I work with Kristof van Tomme at Pronovix and we are keenly interested in implementing a structured API description format that aids API discoverability and eventually, automated integration. In the age of AI we think it is more imperative than ever to have machine readable and discoverable API catalogs available as entry points into an organization's API operations.
We would love to work with anyone to make an agreed upon structured API description format real on many organization portals and promote its use.

**Comment by Kevsy** [comment]
> Hi all, what is the status of apis.json? Any plans to push it further? 

I'm interested in the answer too - I'm editor of an IETF draft, [api-catalog: A well-known URI to help discovery of APIs](https://www.ietf.org/archive/id/draft-ietf-httpapi-api-catalog-00.html) , and was hoping to recommend apis.json as a format for the API Catalog itself.

**Comment by ChristophWeber** [comment]
That's a great RFC @Kevsy! 
I too was thinking that .well-known/ is the better place for apis.json than directly at the root of the web server. Glad to see a push in that direction.
Now we need an answer from @kinlane or @njyx.

**Comment by kinlane** [comment]
Hello. Yes, we are working on proposal for 0.17 currently. Will share ASAP.

**Comment by kinlane** [comment]
We were working on getting more implementations of [WebAPI Schema RFC](https://webapi-discovery.github.io/rfcs/rfc0001.html), but as you note, it has stalled. We'll find some more energy for that as well.

**Comment by ChristophWeber** [comment]
That is great news all around, thank you! Let us know how we can help.

**Comment by kinlane** [comment]
OK, I have published a proposal for .17, please share any thoughts - https://github.com/apis-json/api-json/issues/79 - I am going to step back and consider big picture, and see what else is needed right now for the spec. I have been primarily focused on APIs.io and the Artisanal index.

**Comment by ChristophWeber** [comment]
Thanks, I will comment on the proposal and other issues.
Let's close this issue to keep things tidy.
