### ISSUE TITLE
APIs.json 0.17 Proposal

### ISSUE THREAD

**Issue by kinlane** [api-commons/api-json#79]
I have posted a [draft proposal for APIs.json 0.17](https://github.com/apis-json/apis-json-website/blob/master/format/apisjson_0.17.txt) based upon the work we've been doing with [APIs.io](https://apis.io/).

This release is primarily about adding:

- **aid** - A unique identifier at the collection and api levels.
- **overlays** - References to collection and api level overlays.

After that, I'd like to introduce a handful of property types:

- **GettingStarted**
- **DeprecationPolicy**
- **GraphQLSchema**
- **Integrations**
- **PostmanWorkspace**
- **ServiceLevelAgreement**
- **Versioning**
- **Webhooks**

These property types were identified profiling 75 APIs published to [APIs.io](https://apis.io/).

You can see the latest version in use in the [APIs.json Artisanal project](https://github.com/apis-json/artisanal/tree/main):

- [Stripe](https://github.com/apis-json/artisanal/blob/main/apis/stripe/apis.yml)
- [Twilio](https://github.com/apis-json/artisanal/blob/main/apis/twilio/apis.yml)

Please share your thoughts and comments below, and let's keep iterating on the spec towards 1.0.

**Comment by kinlane** [comment]
I remember, I was going to add an OpenAI plugin manifest -- will update it! #78

**Comment by kinlane** [comment]
Adding from common by Robert Buchanan on LinkedIn  - we should make aid a URN - https://www.issn.org/services/online-services/urn/

**Comment by ChristophWeber** [comment]
**aid** could also be [DSN](https://en.wikipedia.org/wiki/Data_source_name), Data Source Name, which in practice is quite similar to a URN when referencing internet resources. However, a DSN does not have the requirement to register a namespace with IANA or ISSN which I think no API owner will bother to do.

**Comment by kinlane** [comment]
Nice. Thank you @ChristophWeber -- adding into the mix to consider, and I think this gets closer than a URN.

**Comment by philsturgeon** [comment]
@kinlane I was coming to say the same about at least getting a domain involved, because example.org and example.com should not be able to have their aids clash.

**Comment by philsturgeon** [comment]
@kinlane how about a Changelog property which supports those following API Evolution instead of Versioning, and links to thinks like the Bump.sh changelog https://bump.sh/green-turtle/hub/tree-tracker/changes

**Comment by kinlane** [comment]
I've added two items for next version:

- Full Domain in AID - https://github.com/apis-json/api-json/issues/87
- Change Log - https://github.com/apis-json/api-json/issues/88
