### ISSUE TITLE
Website Example Updated from v0.14 to v0.16

### ISSUE THREAD

**Issue by philsturgeon** [api-commons/api-json#84]
Double check I got this right but I took a stab at updating the example on apisjson.org.

https://gist.github.com/philsturgeon/b381e2e6b8633e70a55eb64f07e6e611

**Comment by kinlane** [comment]
Yep, that validates. I pushed the latest [JSON Schema for v0.16 through v0.18](https://github.com/apis-json/api-json/tree/develop/spec) - most of the changes were just adding property types.  

With v0.18 examples I started including all property types to provide a copy / paste example in [JSON](https://github.com/apis-json/api-json/blob/a11814dab15a34e8b9aa6ec9e12c07c241bd8898/spec/apisjson_0.18.txt#L304) or [YAML](https://github.com/apis-json/api-json/blob/a11814dab15a34e8b9aa6ec9e12c07c241bd8898/spec/apisjson_0.18.txt#L544) that people could edit and make their own.

I still have a lot of formatting and consistency issues on latest spec, but will put another round in cleaning up this week -- was all over the place without an accurate JSON Schema.

Thanks for all your work!
